### ISSUE TITLE
PyMol  missing MSMS and can't add it

### ISSUE THREAD

**Issue by eackad** [schlessingerlab/pyvol#5]
I've used the new gui installer and can now get the pyvol1.2.40 screen seen below

![image](https://user-images.githubusercontent.com/17452722/68782827-a1593980-05ff-11ea-8919-0cc0f69fe071.png)

It states there is MSMS. Not matter what radio button I click, that doesn't change and if I enter the path in the Custom, it also does not change. Clicking on Check source does not seem to do anything and Add New source to Path does not work.

MSMS is located at D:\Program_files_windows\msms_win32_6.2.1
How do I get pyvol to look there?

**Comment by rhs2132** [comment]
Thanks for finding all of these bugs. I just redid the code checking for MSMS and pushed it out as v1.2.44 (gui 1.1.11). It should find the bundled MSMS automatically now. And putting that file into the "custom" field and clicking "Change MSMS Path" should add it. 

Alternatively, the MSMS executable can just be added to the path. In Windows, if you right click on the executable and look at the properties, there should be an option to add it to the path. Let me know if the new version of the GUI finds MSMS properly now. And then let me know if you still have trouble running PyVOL on your protein of interest. I'll test the pdb that you sent this weekend.

I also implemented some changes that should make a GUI-less PyVOL usable in PyMOL 1.7.4+, though I haven't had time to properly test them yet.

**Comment by eackad** [comment]
I've tried the full installer on 2.3.3 and gotten an error
![image](https://user-images.githubusercontent.com/17452722/69063628-78132180-09e2-11ea-9c3f-eb5bbc7b2679.png)
stating:
invalid syntax (__init__.py, line 358)
Unable to initialize plugin 'pyvol_gui' (pmg_tk.startup.pyvol_gui).

this was using pyvol-1.2.44-full-installer. It would install but not initialize. I get the same error if I use the pyvol-1.2.44-installer file.

**Comment by orthonalmatrix** [comment]
I tried this on 1.7.x and both say installed but not initialized.
With the 1.2.44 installer I get:
Unable to initialize plugin 'pyvol_gui' (pmg_tk.startup.pyvol_gui).
![image](https://user-images.githubusercontent.com/38046333/69064301-91689d80-09e3-11ea-8e6b-44fcf4f4df4c.png)

With the 1.2.44 full I get the same as above.

**Comment by sangzhe** [comment]
Hi, I'm experiencing the same issue. I was trying to install PyVol 1.3 into my PyMol 2.X. I successfully installed pyvol_gui, but the software can not find MSMS executable anyway. 
![error](https://user-images.githubusercontent.com/12438179/73974363-3794b700-48f2-11ea-9b02-132b0ee3a7f5.PNG)

**Comment by rhs2132** [comment]
I rewrote much of the back end to improve consistency across installations. Could you uninstall and try again using the current installers (1.6.8)? The full vs minimal installers won't make a difference for the described issues here. Let me know if this distribution fixes your issue.

**Comment by sangzhe** [comment]
> I rewrote much of the back end to improve consistency across installations. Could you uninstall and try again using the current installers (1.6.8)? The full vs minimal installers won't make a difference for the described issues here. Let me know if this distribution fixes your issue.

I tried the latest installer, MSMS still cannot be detected.

**Comment by Emily23King** [comment]
Same problem...MSMS cannot be detected.

**Comment by rhs2132** [comment]
I finally tracked down the source of this bug. It turns out that Windows does not propagate changes to the path into the environment used by subprocesses and distutils (see https://stackoverflow.com/questions/5658622/python-subprocess-popen-environment-path if you are interested). So even when the code correctly identifies the executable, it is not able to alter the environment correctly.

I have update the code to alert users to this issue. I'm still brainstorming ways to try to get around this programmatically without hardcoding anything, but for now at least the msms executable will need to be manually added to the system path. I think release 1.7.6 with manual msms path addition should fix all of these issues.

Let me know if you still have any issues with this. I have been testing the code in my standard environments but am working on using virtual environments to replicate naive installations. So my current tests might not correctly replicate your setups yet.

**Comment by rhs2132** [comment]
After thinking about this some more, I think I am going to deploy MSMS as its own conda repository and then invoke the PyMOL conda package manager to independently install MSMS. I used bioconda's packaging of MSMS in the past, but they do not support windows. I'll see if I can roll that out tomorrow.

**Comment by dotimo** [comment]
Dear rhs2132,
I still have the same issue as sangzhe. Even with the latest release 1.7.6. 
The "System MSMS path" is still missing. 
You wrote we have to manually add the MSMS to the system path, but which path is that? I'm not sure about this, sorry. 
Thank you for your update.

**Comment by sue1147** [comment]
I have the same problem now in May 2020.  Can't find MSMS path.  What can I do?

**Comment by bpweiser123** [comment]
Same issue 6/8/20 on Mac high sierra. newest pymol and pyvol releases. MSMS is in the path shown. When I check 'use pyvol msms path' nothing happens.

![Screen Shot 2020-06-08 at 12 45 53 PM](https://user-images.githubusercontent.com/66637042/84057681-04d4fb00-a986-11ea-8528-1ad795e056ac.png)

**Comment by rhs2132** [comment]
There have been way too many issues with msms installation. I am almost done switching the installer over from pip to conda because that allows for installation of non-python code (i.e. msms). I am waiting for approval from conda-forge to add msms and pyvol to the official conda-forge repository in order to take advantage of cross-platform compilation. I hope to have this major update that fixes all msms installation issues out some time this week.

**Comment by rhs2132** [comment]
The conda installation switch is done now. I'm just waiting for approval from conda-forge. The mac and linux versions will probably become available a little before the windows since it's taken a bit longer to get the windows msms approved by conda-forge/bioconda. I am transferring the repository over to an organization lab page but will still be maintaining it.

**Comment by DavPaz** [comment]
Dear comrades,

I had the same problem. MSMS could not be found. What I did to solve the problem and run the plugin was to specify the MSMS system path manually. To do this, I followed the steps indicated on this website (https://datatofish.com/add-python-to-windows-path/). But instead of the specified directory I changed it to my MSMS directory (see the first image). 

 Then I was finally able to calculate the red pocket in the image (see the second image).

I hope this works for you too. 
Good luck! 


![Captura2](https://user-images.githubusercontent.com/85899904/121943861-9d2f5980-cd17-11eb-8bc0-a3d61cbab930.PNG)

![Captura](https://user-images.githubusercontent.com/85899904/121942929-a79d2380-cd16-11eb-973f-03c287a986f0.PNG)

**Comment by diffracteD** [comment]
This is still an annoying issue in linux. Please suggest how to make pyVol know that msms is already in the system. It is so not clear which file to use to show pyvol the msms.py or msms binary whichever it needs.
Please clarify.
Thanks
